[package]
name = "poa"
edition = "2021"
description = "Interchain SDK POA module"
version = "0.0.1"
repository.workspace = true
license.workspace = true

[dependencies]
ixc = { path = ".." }

[dev-dependencies]
ixc_testing = { path = "../testing" }

[lints]
workspace = true

[features]
default = ["std"]
std = []
