[package]
name = "poa"
edition = "2021"
description = "Interchain SDK POA module"
version = "0.0.1"
repository.workspace = true
license.workspace = true

[dependencies]
ixc_core = { path = "../core", version = "0.0.4" }
ixc_core_macros = { path = "../core_macros", version = "0.0.4" }
ixc_schema = { path = "../schema", version = "0.0.4" }

[lints]
workspace = true

[features]
default = ["std"]
std = []
