[workspace]
members = [
    "crates/module_system/core",
    "crates/module_system/core_macros",
    "crates/module_system/collections",
    "crates/module_system/schema",
    "crates/module_system/schema_macros",
    "crates/module_system/message_api",
    "crates/module_system/testing",
    "crates/module_system/util/simple_time",
#    "codecs/proto",
#    "codecs/evm",
#    "vm/wasmtime",
    "crates/vm/api",
    "crates/vm/stf",
    "example",
]

[workspace.package]
repository = "https://github.com/cosmos/cosmos-sdk"
license = "Apache-2.0"
rust-version = "1.81.0"

[workspace.lints]

[workspace.lints.rust]
missing_docs = "deny"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
private_intra_doc_links = "deny"

[package]
name = "ixc"
edition = "2021"
description = "Interchain SDK"
readme = "README.md"
version = "0.0.5"
repository.workspace = true
license.workspace = true

[dependencies]
ixc_core = { path = "crates/module_system/core", version = "0.0.4" }
ixc_schema = { path = "crates/module_system/schema", version = "0.0.4", features = ["use_ixc_macro_path"] }
ixc_message_api = { path = "crates/module_system/message_api", version = "0.0.4" }
collections = { path = "crates/module_system/collections", version = "0.0.4" }
simple_time = { path = "crates/module_system/util/simple_time", version = "0.0.2" }
ixc_core_macros = { path = "crates/module_system/core_macros", version = "0.0.4"}
ixc_schema_macros = { path = "crates/module_system/schema_macros", version = "0.0.3", features = ["use_ixc_macro_path"] }
constcat = "0.5.1"
array-concat = "0.5.3"

[dev-dependencies]
ixc_testing = { path = "testing" }
arrayvec = "0.7.6"
thiserror = "1.0.63"
num_enum = "0.7.3"
mockall = "0.13.0"

[lib]
doctest = false

[lints]
workspace = true

[features]
default = []

[profile.release]
lto = true

[[example]]
name = "counter"
crate-type = ["cdylib"]
