[package]
name = "ixc-codec-solidity-abi"
version = "0.0.1"
edition = "2021"
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
ixc_schema = { path = "../../schema" }
alloy-sol-types = "0.8.5"

[lints]
workspace = true
