name: WebAssembly Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        profile: minimal

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('**/Cargo.lock') }}

    - name: Build WebAssembly
      run: cargo build --target wasm32-unknown-unknown
      
    # Optional: Add testing if you have wasm tests
    # - name: Run tests
    #   run: cargo test --target wasm32-unknown-unknown

    # Optional: Archive wasm artifacts
    - name: Archive wasm artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wasm-build
        path: target/wasm32-unknown-unknown/debug/*.wasm